name: weatherapp
description: A Weather forecast app.

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  # Service locator
  get_it: ^7.2.0
  # Bloc for state management
  flutter_bloc: ^8.0.1
  # Value equality
  equatable: ^2.0.3
  # Functional programming thingies
  dartz: ^0.10.1
  # Remote API
  internet_connection_checker: ^0.0.1+4
  http: ^0.13.4
  # Refresh result
  pull_to_refresh: ^2.0.0
  # to cache network images
  cached_network_image: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0

flutter:
  uses-material-design: true
